<?php

use HelpCrunch\HelpCrunch\Block\WidgetBlock;

/** @var $block WidgetBlock  */
$dataHelper = $block->getDataHelper();
?>
<?php if ($dataHelper->hasSettings()) : ?>
  <script type="text/javascript">
    (function(w,d){
      w.HelpCrunch=function(){w.HelpCrunch.q.push(arguments)};w.HelpCrunch.q=[];
      function r(){var s=document.createElement('script');s.async=1;s.type='text/javascript';s.src='https://widget.helpcrunch.com';(d.body||d.head).appendChild(s);}
      if(w.attachEvent){w.attachEvent('onload',r)}else{w.addEventListener('load',r,false)}
    })(window, document)
  </script>

  <script type="text/javascript">
    HelpCrunch('init', '<?php echo $dataHelper->getOrganizationName(); ?>', {
      applicationId: <?php echo $dataHelper->getApplicationId(); ?>,
      applicationSecret: '<?php echo $dataHelper->getApplicationSecret(); ?>',
        <?php if ($dataHelper->isLoggedIn()) : ?>
          user: {
            user_id: <?php echo $dataHelper->getCustomerId(); ?>,
            <?php if ($dataHelper->getCustomerName()) : ?>
              name: '<?php echo $dataHelper->getCustomerName(); ?>',
            <?php endif; ?>
            <?php if ($dataHelper->getCustomerEmail()) : ?>
              email: '<?php echo $dataHelper->getCustomerEmail(); ?>',
            <?php endif; ?>
          }
        <?php endif; ?>
    });

    HelpCrunch('showChatWidget');
  </script>
<?php endif; ?>
